esphome:
  includes:
    - packages/jb_irrigation.pkg/jb_irrigation.h
  on_boot:
    - priority: -100
      then:
        - lambda: |-
            JBHeating::init(30, { ${prefix_entity_id}${zone1_id}_valve,
                                  ${prefix_entity_id}${zone2_id}_valve,
                                  ${prefix_entity_id}${zone3_id}_valve,
                                  ${prefix_entity_id}${zone4_id}_valve
                                },
                            ${max_irrigation_duration});
        - if:
            condition:
              lambda: 'return JBHeating::isFailureDetected();'
            then:
              - logger.log:
                  format: 'Failure detected. This means that watering cycle was interrupted. Report to HomeAssistant will be submitted'
                  level: WARN
                  tag: jb_irrigation
              - lambda: std::fill_n(id(jb_valves_countdown), 10, 0);
              - wait_until:
                  api.connected:
              - delay: 1sec
              - homeassistant.event:
                  event: esphome.irrigation_failure
                  data:
                    controller_id: ${node_name}
            else:
              - logger.log:
                  format: 'Failure check: clear'
                  level: INFO
                  tag: jb_irrigation

# Dallas
dallas:
  - pin: GPIO26
    id: dallas_hub0
    update_interval: 3min

# Example configuration entry
interval:
  - interval: 30sec
    then:
      - lambda: JBHeating::handleCountdown();

globals:
  - id: jb_valves_countdown
    type: int[10]
    restore_value: no
    initial_value: '{0,0,0,0,0,0,0,0,0,0}'

api:
  services:
    - service: start_irrigation
      variables:
        duration: int
        valve_id: string
      then:
        - lambda: JBHeating::startIrrigation(duration, valve_id);

# Switches
switch:
  - platform: gpio
    internal: "${not_expose_valves}"
    name: "${prefix_name} ${zone1_name} valve"
    id: "${prefix_entity_id}${zone1_id}_valve"
    pin:
      number: GPIO18
      mode: OUTPUT
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:water-pump
    on_turn_on:
      - homeassistant.event:
          event: esphome.irrigation_started
          data:
            controller_id: ${node_name}
            zone_id: ${zone1_id}
            zone: "${node_name}.${zone1_id}"
            valve: "${node_name}.${zone1_id}_valve"
            zone_name: "${zone1_name}"
      - delay: 1sec
      - if:
          condition:
            lambda: return !JBHeating::ensureValveOpenTimeIsLimited(${prefix_entity_id}${zone1_id}_valve);
          then:
            - homeassistant.event:
                event: esphome.irrigation_manual_valve_open
                data:
                  controller_id: ${node_name}
                  zone_id: ${zone1_id}
                  zone: "${node_name}.${zone1_id}"
                  valve: "${node_name}.${zone1_id}_valve"
                  limit: "${max_irrigation_duration}"
    on_turn_off:
      - homeassistant.event:
          event: esphome.irrigation_stopped
          data:
            controller_id: ${node_name}
            zone_id: ${zone1_id}
            zone: "${node_name}.${zone1_id}"
            valve: "${node_name}.${zone1_id}_valve"
            zone_name: "${zone1_name}"

  - platform: gpio
    internal: "${not_expose_valves}"
    name: "${prefix_name} ${zone2_name} valve"
    id: "${prefix_entity_id}${zone2_id}_valve"
    pin:
      number: GPIO19
      mode: OUTPUT
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:water-pump
    on_turn_on:
      - homeassistant.event:
          event: esphome.irrigation_started
          data:
            controller_id: ${node_name}
            zone_id: ${zone2_id}
            zone: "${node_name}.${zone2_id}"
            valve: "${node_name}.${zone2_id}_valve"
            zone_name: "${zone2_name}"
      - delay: 1sec
      - if:
          condition:
            lambda: return !JBHeating::ensureValveOpenTimeIsLimited(${prefix_entity_id}${zone2_id}_valve);
          then:
            - homeassistant.event:
                event: esphome.irrigation_manual_valve_open
                data:
                  controller_id: ${node_name}
                  zone_id: ${zone1_id}
                  zone: "${node_name}.${zone2_id}"
                  valve: "${node_name}.${zone2_id}_valve"
                  limit: "${max_irrigation_duration}"
    on_turn_off:
      - homeassistant.event:
          event: esphome.irrigation_stopped
          data:
            controller_id: ${node_name}
            zone_id: ${zone2_id}
            zone: "${node_name}.${zone2_id}"
            valve: "${node_name}.${zone2_id}_valve"
            zone_name: "${zone2_name}"
  - platform: gpio
    internal: "${not_expose_valves}"
    name: "${prefix_name} ${zone3_name} valve"
    id: "${prefix_entity_id}${zone3_id}_valve"
    pin:
      number: GPIO33
      mode: OUTPUT
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:water-pump
    on_turn_on:
      - homeassistant.event:
          event: esphome.irrigation_started
          data:
            controller_id: ${node_name}
            zone_id: ${zone3_id}
            zone: "${node_name}.${zone3_id}"
            valve: "${node_name}.${zone3_id}_valve"
            zone_name: "${zone3_name}"
      - delay: 1sec
      - if:
          condition:
            lambda: return !JBHeating::ensureValveOpenTimeIsLimited(${prefix_entity_id}${zone3_id}_valve);
          then:
            - homeassistant.event:
                event: esphome.irrigation_manual_valve_open
                data:
                  controller_id: ${node_name}
                  zone_id: ${zone1_id}
                  zone: "${node_name}.${zone3_id}"
                  valve: "${node_name}.${zone3_id}_valve"
                  limit: "${max_irrigation_duration}"
    on_turn_off:
      - homeassistant.event:
          event: esphome.irrigation_stopped
          data:
            controller_id: ${node_name}
            zone_id: ${zone3_id}
            zone: "${node_name}.${zone3_id}"
            valve: "${node_name}.${zone3_id}_valve"
            zone_name: "${zone3_name}"
  - platform: gpio
    internal: "${not_expose_valves}"
    name: "${prefix_name} ${zone4_name} valve"
    id: "${prefix_entity_id}${zone4_id}_valve"
    pin:
      number: GPIO23
      mode: OUTPUT
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:water-pump
    on_turn_on:
      - homeassistant.event:
          event: esphome.irrigation_started
          data:
            controller_id: ${node_name}
            zone_id: ${zone4_id}
            zone: "${node_name}.${zone4_id}"
            valve: "${node_name}.${zone4_id}_valve"
            zone_name: "${zone4_name}"
      - delay: 1sec
      - if:
          condition:
            lambda: return !JBHeating::ensureValveOpenTimeIsLimited(${prefix_entity_id}${zone4_id}_valve);
          then:
            - homeassistant.event:
                event: esphome.irrigation_manual_valve_open
                data:
                  controller_id: ${node_name}
                  zone_id: ${zone4_id}
                  zone: "${node_name}.${zone4_id}"
                  valve: "${node_name}.${zone4_id}_valve"
                  limit: "${max_irrigation_duration}"
    on_turn_off:
      - homeassistant.event:
          event: esphome.irrigation_stopped
          data:
            controller_id: ${node_name}
            zone_id: ${zone4_id}
            zone: "${node_name}.${zone4_id}"
            valve: "${node_name}.${zone4_id}_valve"
            zone_name: "${zone4_name}"
